# Generated by Django 5.2.17 on 2026-09-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservocabularyprogress",
            name="card_state",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("learning", "learning"),
                    ("review", "review"),
                    ("relearning", "relearning"),
                ],
                default="review",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="uservocabularyprogress",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uservocabularyprogress",
            name="learning_step",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
