# Generated by Django 5.2.17 on 2026-09-22 13:07

import apps.core.constants
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0003_remove_vocabulary_vocabulary__bjt_lev_06d2b7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('question_count', models.PositiveSmallIntegerField(default=0, help_text='ĐẾM THEO BẢNG ĐÁP ÁN trang 52-54, không theo mục lục (mục lục sai).')),
                ('source_note', models.CharField(blank=True, default='Thaolejp - Khoa BJT Kinh ngu (04/2025)', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bộ đề kính ngữ',
                'verbose_name_plural': 'Bộ đề kính ngữ',
                'ordering': ['display_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(help_text='Số của 問題; đoạn thứ 2 trở đi đánh tiếp.')),
                ('instruction_jp', models.TextField(blank=True)),
                ('passage_jp', models.TextField(blank=True, help_text='Chỉ điền khi có đoạn văn dùng chung cho nhiều câu.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exercise_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='keigo.exerciseset')),
            ],
            options={
                'verbose_name': 'Phần đề (問題)',
                'verbose_name_plural': 'Phần đề (問題)',
                'ordering': ['exercise_set_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='KeigoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('style_code', models.CharField(blank=True, choices=apps.core.constants.keigo_style_choices, help_text="MasterCode '14'. Để trống với chương nội dung hỗn hợp.", max_length=20)),
                ('summary_vi', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('source_note', models.CharField(blank=True, default='Thaolejp - Khoa BJT Kinh ngu (04/2025)', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chương kính ngữ',
                'verbose_name_plural': 'Chương kính ngữ',
                'ordering': ['display_order', 'slug'],
            },
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_sets', to='keigo.keigolesson'),
        ),
        migrations.CreateModel(
            name='KeigoPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='vd sonkei-o-go-ni-naru', max_length=60, unique=True)),
                ('style_code', models.CharField(blank=True, choices=apps.core.constants.keigo_style_choices, max_length=20)),
                ('title', models.CharField(help_text='Chép nguyên tiêu đề mẫu trong sách.', max_length=120)),
                ('formation', models.CharField(blank=True, help_text='vd お/ご + Vます形 + になる', max_length=255)),
                ('explanation_vi', models.TextField(blank=True, help_text='Sách gốc KHÔNG có giải thích tiếng Việt — tự viết thêm.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='keigo.keigolesson')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mẫu ngữ pháp kính ngữ',
                'verbose_name_plural': 'Mẫu ngữ pháp kính ngữ',
                'ordering': ['lesson_id', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='KeigoExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentence_jp', models.CharField(help_text='Có cú pháp ruby {漢字|かんじ}.', max_length=400)),
                ('sentence_vi', models.CharField(blank=True, max_length=400)),
                ('speaker', models.CharField(blank=True, help_text='A / B / 客 / 係員 ...', max_length=30)),
                ('is_correct', models.BooleanField(default=True, help_text='False = câu bị đánh dấu ×.')),
                ('pair_group', models.PositiveSmallIntegerField(blank=True, help_text='Gom các dòng cùng một hội thoại / cùng một cặp ×–○. Đánh số riêng trong mỗi mẫu.', null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='keigo.keigopattern')),
            ],
            options={
                'verbose_name': 'Câu ví dụ kính ngữ',
                'verbose_name_plural': 'Câu ví dụ kính ngữ',
                'ordering': ['pattern_id', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='KeigoPhrasePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pair_type', models.CharField(choices=apps.core.constants.keigo_pair_type_choices, max_length=20)),
                ('group_label', models.CharField(blank=True, max_length=120)),
                ('casual', models.CharField(blank=True, help_text='Vế trái / vế SAI.', max_length=200)),
                ('polite', models.CharField(help_text='Vế phải / vế ĐÚNG / cụm từ đệm.', max_length=200)),
                ('note_vi', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_pairs', to='keigo.keigolesson')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cặp từ kính ngữ',
                'verbose_name_plural': 'Cặp từ kính ngữ',
                'ordering': ['pair_type', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='KeigoVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plain_form', models.CharField(help_text='vd 言う, 風邪を引く', max_length=50)),
                ('reading', models.CharField(blank=True, max_length=80)),
                ('meaning_vi', models.CharField(blank=True, max_length=150)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Động từ gốc',
                'verbose_name_plural': 'Động từ gốc',
                'ordering': ['display_order', 'plain_form'],
            },
        ),
        migrations.CreateModel(
            name='KeigoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style_code', models.CharField(choices=apps.core.constants.keigo_style_choices, max_length=20)),
                ('form', models.CharField(help_text='vd おっしゃる, お読みになる', max_length=80)),
                ('reading', models.CharField(blank=True, max_length=120)),
                ('is_irregular', models.BooleanField(default=False, help_text="True = thuộc bảng 'các trường hợp đặc biệt' (tr.4 / tr.7 / tr.9).")),
                ('note_vi', models.CharField(blank=True, help_text='Ghi chú in màu đỏ trong ô của sách, vd （自分が一方的に行う行為の場合）.', max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keigo_forms', to='vocabulary.vocabulary')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='keigo.keigoverb')),
            ],
            options={
                'verbose_name': 'Dạng kính ngữ',
                'verbose_name_plural': 'Dạng kính ngữ',
                'ordering': ['verb_id', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='vd bt03-q07, lt-m2-q05', max_length=30, unique=True)),
                ('number', models.PositiveSmallIntegerField(help_text='Số câu in trong sách.')),
                ('question_type', models.CharField(choices=apps.core.constants.question_type_choices, max_length=20)),
                ('context_note', models.CharField(blank=True, help_text='（レストランで）...', max_length=120)),
                ('stem_jp', models.TextField(help_text='Chỗ trống ký hiệu ____ , ô sao __★__ .')),
                ('star_position', models.PositiveSmallIntegerField(blank=True, help_text='Vị trí ô ★ (1-4). CHỈ dạng ordering.', null=True)),
                ('correct_order', models.CharField(blank=True, help_text='4 chữ số, vd 4321. CHỈ dạng ordering.', max_length=8)),
                ('explanation_vi', models.TextField(blank=True, help_text='Sách không có lời giải — viết dần.')),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='keigo.exercisesection')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'verbose_name_plural': 'Câu hỏi',
                'ordering': ['section_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(help_text='Số thứ tự in trong sách (1-4).')),
                ('text_jp', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='keigo.question')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phương án',
                'verbose_name_plural': 'Phương án',
                'ordering': ['question_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exercise_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='keigo.exerciseset')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keigo_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lượt làm bài kính ngữ',
                'verbose_name_plural': 'Lượt làm bài kính ngữ',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_order', models.CharField(blank=True, help_text='Dạng ordering.', max_length=8)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='keigo.userexerciseattempt')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='keigo.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='keigo.questionoption')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Câu trả lời kính ngữ',
                'verbose_name_plural': 'Câu trả lời kính ngữ',
                'ordering': ['attempt_id', 'question_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='exercisesection',
            constraint=models.UniqueConstraint(fields=('exercise_set', 'number'), name='uniq_keigo_section'),
        ),
        migrations.AddConstraint(
            model_name='keigoexample',
            constraint=models.UniqueConstraint(fields=('pattern', 'sentence_jp'), name='uniq_keigo_example'),
        ),
        migrations.AddConstraint(
            model_name='keigophrasepair',
            constraint=models.UniqueConstraint(fields=('pair_type', 'casual', 'polite'), name='uniq_keigo_phrase_pair'),
        ),
        migrations.AddConstraint(
            model_name='keigoverb',
            constraint=models.UniqueConstraint(fields=('plain_form', 'reading'), name='uniq_keigo_verb_form_reading'),
        ),
        migrations.AddIndex(
            model_name='keigoform',
            index=models.Index(fields=['style_code', 'is_irregular'], name='keigo_keigo_style_c_4d936b_idx'),
        ),
        migrations.AddConstraint(
            model_name='keigoform',
            constraint=models.UniqueConstraint(fields=('verb', 'style_code', 'form'), name='uniq_keigo_form'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'position'), name='uniq_keigo_option_position'),
        ),
        migrations.AddIndex(
            model_name='userexerciseattempt',
            index=models.Index(fields=['user', '-started_at'], name='keigo_usere_user_id_f605e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='userexerciseattempt',
            constraint=models.UniqueConstraint(fields=('user', 'exercise_set', 'started_at'), name='uniq_keigo_attempt'),
        ),
        migrations.AddConstraint(
            model_name='userquestionanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_keigo_answer'),
        ),
    ]
