# Generated by Django 5.2.17 on 2026-09-13 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_type', models.CharField(help_text="Nhóm code, vd '01' = danh hiệu đóng góp, '05' = cấp độ BJT.", max_length=10)),
                ('code', models.CharField(help_text="Mã trong nhóm, vd '001'.", max_length=10)),
                ('code_name', models.CharField(help_text="Tên hiển thị, vd 'Tân Binh'.", max_length=150)),
                ('mother_code', models.CharField(blank=True, help_text='Mã cha TRONG CÙNG code_type — null = cấp cao nhất.', max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Master code',
                'verbose_name_plural': 'Master codes',
                'ordering': ['code_type', 'sort_order', 'code'],
                'unique_together': {('code_type', 'code')},
            },
        ),
    ]
