# Generated by Django 5.2.17 on 2026-09-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='proposed_bjt_level',
        ),
    ]
