# Generated by Django 5.2.17 on 2026-09-16 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0003_remove_vocabulary_vocabulary__bjt_lev_06d2b7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_type_code', models.CharField(max_length=10)),
                ('status_code', models.CharField(default='001', max_length=10)),
                ('description', models.TextField(help_text='Người dùng mô tả lỗi gặp phải.')),
                ('suggested_fix', models.CharField(blank=True, help_text='Đề xuất sửa (tuỳ chọn).', max_length=255)),
                ('page_path', models.CharField(blank=True, max_length=255)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('admin_response', models.TextField(blank=True, help_text='Phản hồi hiển thị cho người báo.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_reports', to='vocabulary.vocabulary')),
            ],
            options={
                'verbose_name': 'Error report',
                'verbose_name_plural': 'Error reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status_code'], name='error_repor_status__35fce9_idx'), models.Index(fields=['vocabulary', 'status_code'], name='error_repor_vocabul_323010_idx')],
            },
        ),
    ]
