# Generated by Django 5.2.17 on 2026-09-13 04:18

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Bật extension pg_trgm TRƯỚC khi tạo index gin_trgm_ops.
        # Trên Supabase, role `postgres` có quyền chạy lệnh này; nếu môi trường
        # nào đó không cho, bật tay ở Dashboard > Database > Extensions rồi
        # chạy lại migrate — `CREATE EXTENSION IF NOT EXISTS` là no-op.
        TrigramExtension(),
        migrations.AddIndex(
            model_name='vocabulary',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('word'), name='gin_trgm_ops'), name='vocab_word_trgm'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('reading'), name='gin_trgm_ops'), name='vocab_reading_trgm'),
        ),
    ]
