# Generated by Django 5.2.17 on 2026-09-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_trigram_search'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vocabulary',
            name='vocabulary__bjt_lev_06d2b7_idx',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='bjt_level',
        ),
        migrations.AddField(
            model_name='topic',
            name='name_ja',
            field=models.CharField(blank=True, help_text="Tên tiếng Nhật, vd '会議・打合せ'. Để trống thì UI chỉ hiện tên tiếng Việt.", max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(help_text="Tên tiếng Việt, vd 'Họp hành'.", max_length=100),
        ),
    ]
