# Generated by Django 5.2.17 on 2026-09-13 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lines_per_word', models.PositiveSmallIntegerField(default=2)),
                ('show_guide_character', models.BooleanField(default=True)),
                ('show_reading_and_meaning', models.BooleanField(default=True)),
                ('pdf_file', models.FileField(upload_to='practice_sheets/')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PracticeSheetWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record (null = created by system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_links', to='practice_sheets.practicesheet')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sheet_links', to='vocabulary.vocabulary')),
            ],
            options={
                'verbose_name': 'PracticeSheet-Vocabulary link',
                'unique_together': {('sheet', 'vocabulary')},
            },
        ),
        migrations.AddField(
            model_name='practicesheet',
            name='words',
            field=models.ManyToManyField(related_name='practice_sheets', through='practice_sheets.PracticeSheetWord', to='vocabulary.vocabulary'),
        ),
    ]
