# Generated by Django 5.2.17 on 2026-09-14 13:24

import apps.core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice_sheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesheet",
            name="custom_words",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="practicesheet",
            name="include_answer_key",
            field=models.BooleanField(
                default=True, help_text="Thêm trang đáp án ở cuối để tự chấm."
            ),
        ),
        migrations.AddField(
            model_name="practicesheet",
            name="include_sentence_box",
            field=models.BooleanField(
                default=True, help_text="Chừa thêm một dòng kẻ để tự đặt câu với từ đó."
            ),
        ),
        migrations.AddField(
            model_name="practicesheet",
            name="recall_direction",
            field=models.CharField(
                blank=True,
                choices=apps.core.constants.recall_direction_choices,
                help_text="MasterCode code_type '11'. Để trống với phiếu luyện viết.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="practicesheet",
            name="sheet_type",
            field=models.CharField(
                choices=apps.core.constants.sheet_type_choices,
                default="writing",
                help_text="MasterCode code_type '10'.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="practicesheet",
            name="shuffle_order",
            field=models.BooleanField(
                default=False,
                help_text="Xáo trộn thứ tự để in lại cùng danh sách mà không thuộc lòng theo vị trí.",
            ),
        ),
    ]
